# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install package with it's dependencies
      run: make install
      env:
          CI: true
    - name: Linter code check
      run: make lint
    - name: Test & publish code coverage
      # Publish code coverage on Code Climate
      # https://github.com/paambaati/codeclimate-action
      uses: paambaati/codeclimate-action@v2.6.0
      # Add Code Climate secret key
      env:
        CC_TEST_REPORTER_ID: ${{secrets.TEST_ID_REP_3_CODE_CLIMATE}}
      with:
        coverageCommand: make test-coverage
        debug: true
